### ISSUE TITLE
Column Datatype issue

### ISSUE THREAD

**Issue by mythodeia** [christopherney/SQPersist#4]
Hello
i have an object with 3 properties set as nonatomic,copy & NSString. When i create the entity for that object i see that the table was created with all the columns set as integers.
if i revert to nonatomic,strong then the columns are created as TEXT, which is correct.

i did a code check and found that the property attributes for e.g one column where
``` T@"NSString",C,N,V_templateID ```

can you explain why its translated to int in the db?

thanks

**Comment by christopherney** [comment]
Hello, can you send me the .h file of your object ?

**Comment by mythodeia** [comment]
here you go
```
#import <Foundation/Foundation.h>
#import "SQPObject.h"

@interface AQSigned : SQPObject

@property (nonatomic, copy) NSString *userID;
@property (nonatomic, copy) NSString *typeID;
@property (nonatomic, copy) NSString *measureID;

@end
```

thanks for your time

**Comment by christopherney** [comment]
Thank, I think I found the problem, is copy option.

If you replace it by strong it's will be work. I will update the function to manage copy properties.

**Comment by christopherney** [comment]
The problem come form SQPProperty.m line 54

Replace : 

if ([self string:propertyAttributes containsSubString:@",&,"]) {

By 

if ([self string:propertyAttributes containsSubString:@",&,"] || [self string:propertyAttributes containsSubString:@",C,"]) {

**Comment by mythodeia** [comment]
yes i saw that there was no copy management just now. Yes strong makes it work fine.
Please update the library. Thanks for your time and for this library

**Comment by christopherney** [comment]
I will add it tonight.

**Comment by mythodeia** [comment]
:+1:

**Comment by christopherney** [comment]
pod update is Ready !!!

**Comment by mythodeia** [comment]
thanks
