### ISSUE TITLE
Strong - ReadOnly

### ISSUE THREAD

**Issue by mythodeia** [christopherney/SQPersist#5]
In case of a strong/readOnly property e.g 
```@property (nonatomic, strong, readonly) UIImage *sourceImage;```
the database table is populated with a column type INT.

this can be fixed by adding this ``` [self string:propertyAttributes containsSubString:@",R,"]``` in the if statement inside the method ```getPropertyType``` of the ```SQPProperty.m``` file.
In my case i added this:
```@property (nonatomic) BOOL isReadOnly;``` 
to match your coding prerequisites. Plus it would be cool to have it handy if needed.

thanks

**Comment by christopherney** [comment]
Hi, 

Thank ou for your help. I will add this option tonight, and generate a new release.

**Comment by mythodeia** [comment]
:+1:

**Comment by mythodeia** [comment]
When you find some time please add this to your project. If you think i have missed something please let me know so we can discuss it. Thanks

**Comment by mythodeia** [comment]
@christopherney any updates on this?

**Comment by mythodeia** [comment]
@christopherney did you have any time to add this to your code?

**Comment by christopherney** [comment]
Hi, I just add the isReadonly property. Release 1.0.5.

**Comment by mythodeia** [comment]
thanks :+1:
