### ISSUE TITLE
SQLCipher compatibility 

### ISSUE THREAD

**Issue by johnmillz** [christopherney/SQPersist#6]
Would love to make use of SQPersist for my project but I have a requirement to encrypt the database file. SQLCipher is an encryption option available for iOS. I noticed FMDB is a dependency for this project; it has an FMDB/SQLCipher subspec. What's the best way to go about using this subspec as a dependency instead of the standard FMDB?

Thanks

**Comment by christopherney** [comment]
Hi,

I know SQLCipher, but I never used it. SQPersist have no dependency with. If you want, you can fork the repository and add this option.

If it's work great, I will merge it in master branch, and release it for Cocoa Pod.

**Comment by johnmillz** [comment]
Hey, I've forked the project and made a pull request.
For usage I do the following before using the database:

```Objective-C
    [[SQPDatabase sharedInstance] setupDatabaseWithName:DatabaseStorageFilename];
    [[[SQPDatabase sharedInstance] database]setKey:[DatabasePassphraseManager passphrase]];
```

**Comment by johnmillz** [comment]
@christopherney How are you getting on with this?
