### ISSUE TITLE
SQPFetchAllWhere with LIKE 

### ISSUE THREAD

**Issue by pingusNikalex** [christopherney/SQPersist#8]
Can we use LIKE in SQPFetchAllWhere?
If yes, can you write any example?

**Comment by christopherney** [comment]
Yes, it's possible:

https://github.com/christopherney/SQPersist/blob/master/Example/Example/RootTableViewController.m
`
    NSString *searchText = searchBar.text;
    self.where = [NSString stringWithFormat:@"name LIKE '%%%@%%'", searchText];
    self.items = [Car SQPFetchAllWhere:self.where orderBy:self.orderProperty];
`
